_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
critic_layer_sizes:
    value:
        - 2048
        - 1024
        - 1024
        - 1024
critic_lr:
    value: 0.0004
exp_buffer_size:
    value: 150000
gae_gamma:
    value: 0.99
gae_lambda:
    value: 0.95
min_inference_size:
    value: 31
n_proc:
    value: 34
policy_layer_sizes:
    value:
        - 2048
        - 1024
        - 1024
        - 1024
policy_lr:
    value: 0.0004
ppo_batch_size:
    value: 50000
ppo_clip_range:
    value: 0.2
ppo_ent_coef:
    value: 0.01
ppo_epochs:
    value: 4
ppo_minibatch_size:
    value: 50000
shm_buffer_size:
    value: 8192
standardize_obs:
    value: false
standardize_returns:
    value: true
timestep_limit:
    value: 1000000000000
ts_per_iteration:
    value: 50000
